name             'wrapper_minecraft'
maintainer       'Ryan Hass'
maintainer_email 'ryan at invalidchecksum d ot ne t'
license          'Apache 2.0'
description      'Installs/Configures wrapper_minecraft'
long_description 'Installs/Configures wrapper_minecraft'
version          '0.1.0'

depends 'apt'
depends 'minecraft'
depends 'java'
